import type { Metadata } from "next";
import { Inter, Bebas_Neue, Playfair_Display } from 'next/font/google';
import "./globals.css";
import { Providers } from "./providers";
import { Box } from '@mui/material';

const inter = Inter({ subsets: ['latin'] });
const bebasNeue = Bebas_Neue({ 
  weight: '400',
  subsets: ['latin'],
  variable: '--font-bebas-neue',
});
const playfairDisplay = Playfair_Display({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-playfair-display',
  style: ['normal', 'italic'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${bebasNeue.variable} ${playfairDisplay.variable}`}>
        <Providers>
          <Box
            sx={{
              minHeight: '100vh',
              display: 'flex',
              flexDirection: 'column',
            }}
          >
            {children}
          </Box>
        </Providers>
      </body>
    </html>
  );
}
